apiVersion: apps/v1
kind: Deployment
metadata:
  name: nugetserver
  labels:
    app: nugetserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nugetserver
    spec:
      containers:
      - name: nugetserver
        image: mrjamiebowman/nuget-server-windows-server-core
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: nugetserver          

---

apiVersion: v1
kind: Service
metadata:
  name: nugetserver
spec:
  type: LoadBalancer
  ports:  
  - protocol: TCP
    port: 80
  selector:
    app: nugetserver