---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nugetserver 
  name: nugetserver 
spec:
  ports:
  - port: 80 
    protocol: TCP
    name: port80
    targetPort: 80 
  - port: 443 
    protocol: TCP
    name: port443
    targetPort: 443
  selector:
    name: nugetserver
  type: NodePort
  
---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nugetserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nugetserver
  template:
    metadata:
      labels:
        app: nugetserver
    spec:
      containers:
      - name: nugetserver
        image: mrjamiebowman/nuget-server-windows-server-core
        ports:
          - name: nugetserver
            containerPort: 80
